version: '3.4'
services:
#  Optional
#  pdf-toolkit-repo-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: pdf-toolkit-repo-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  pdf-toolkit-repo-acs:
    image: alfresco-content-services-pdf-toolkit-repo:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - pdf-toolkit-repo-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - pdf-toolkit-repo-postgres
  pdf-toolkit-repo-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    ports:
      - "${postgres.port}:5432"
    volumes:
      - pdf-toolkit-repo-db-volume:/var/lib/postgresql/data
  pdf-toolkit-repo-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: pdf-toolkit-repo-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: pdf-toolkit-repo-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - pdf-toolkit-repo-ass-volume:/opt/alfresco-search-services/contentstore
      - pdf-toolkit-repo-ass-volume:/opt/alfresco-search-services/data
volumes:
  pdf-toolkit-repo-acs-volume:
    external: true
  pdf-toolkit-repo-db-volume:
    external: true
  pdf-toolkit-repo-ass-volume:
    external: true